version: '3'

services:
  integration_tests:
    build:
      context: .
      dockerfile: ./../project/Dockerfile.test
    ports:
      - "8083:80"
    volumes:
      - ./:/go/src/github.com/amirrmonfared/testMicroServices/project