// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type User struct {
	ID         int32          `json:"id"`
	Email      sql.NullString `json:"email"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Password   sql.NullString `json:"password"`
	UserActive sql.NullInt32  `json:"user_active"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}
