// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	GetAll(ctx context.Context) ([]User, error)
}

var _ Querier = (*Queries)(nil)
